
[colors]
draw_bold_text_with_bright_colors = false

[colors.cursor]
cursor = "#EDCF4F"
# white text for dark background
# text = "#FFFFFA"

# [colors.bright]
# black = "#595B59"
# blue = "#135979"
# cyan = "#76BBCA"
# green = "#34A853"
# magenta = "#604291"
# red = "#D18FA6"
# white = "#B2B5AE"
# yellow = "#78592F"

# [colors.normal]
# black = "#343935"
# blue = "#4C9AD4"
# cyan = "#389AAD"
# green = "#7BB75B"
# magenta = "#A57FC4"
# red = "#CF3F61"
# white = "#FFFFFA"
# yellow = "#E9B32A"

# [colors.primary]
# # dark background
# background = "#1E1E1E"

[cursor]
style = "Block"

[font]
size = 18

# [font.bold]
# family = "JetBrainsMono Nerd Font"
# style = "Bold"
#
# [font.italic]
# family = "JetBrainsMono Nerd Font"
# style = "Italic"
#
# [font.normal]
# family = "JetBrainsMono Nerd Font"
# style = "Regular"

[font.bold]
family = "RecMonoCasual Nerd Font"
style = "Bold"

[font.italic]
family = "RecMonoCasual Nerd Font"
style = "Italic"

[font.normal]
family = "RecMonoCasual Nerd Font"
style = "Regular"


[[keyboard.bindings]]
chars = "\u0002,"
key = "Comma"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002s"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002%"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\""
key = "N"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002d"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002n"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = """
\u001B:w
"""
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002!"
key = "T"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002z"
key = "Z"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002{"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002 "
key = "Space"
mods = "Option"

[window]
decorations = "buttonless"

[window.padding]
x = 15
y = 15

[general]
live_config_reload = true

# Colors (Gruvbox light)

# Default colors
# [colors.primary]
# # hard contrast
# #background = '#f9f5d7'
# # medium contrast
# background = '#fbf1c7'
# # soft contrast
# # background = '#f2e5bc'
# foreground = '#3c3836'
# # Normal colors
# [colors.normal]
# black = '#fbf1c7'
# red = '#cc241d'
# green = '#98971a'
# yellow = '#d79921'
# blue = '#458588'
# magenta = '#b16286'
# cyan = '#689d6a'
# white = '#7c6f64'
# # Bright colors
# [colors.bright]
# black = '#928374'
# red = '#9d0006'
# green = '#79740e'
# yellow = '#b57614'
# blue = '#076678'
# magenta = '#8f3f71'
# cyan = '#427b58'
# white = '#3c3836'

# Colors (Gruvbox dark)

# Default colors
[colors.primary]
# soft contrast background = '#282828'
background = '#1d2021'
# soft contrast background = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
# bright color used as normal ones
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'


# Bright colors
[colors.bright]
# darker color used as bright ones
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'
